### ISSUE TITLE
Widget size doesn't respect base dimentions

### ISSUE THREAD

**Issue by toddq** [Shopify/dashing#110]
I have a widget that shows news headlines and summary from rss feeds.  Sometimes content doesn't fit nicely and the widget just grows to accomodate it, which then makes it over or under-lap neighboring widgets.

I tried adding `overflow: hidden` to the `li` element, which _would_ accomplish the behavior I'd prefer to see, but `.gs_w` is using `display: table`, so my overflow gets ignored.

Can something be changed so that my values for `Dashing.widget_base_dimensions` are respected and anything that doesn't fit just gets hidden?

**Comment by pferreir** [comment]
:+1: for this issue.

Based on @toddq's solution, I find this less intrusive:

```css
.gridster li {
    overflow: hidden;
    display:  list-item;
}

.gridster li div {
     display: table;
     width: 100%;
     height: 100%;
}
```

Still, a proper fix would be much better.
