### ISSUE TITLE
Figaro gem on dashing

### ISSUE THREAD

**Issue by michaelachrisco** [Shopify/dashing#515]
It would be nice to see support for Figaro so github private tokens can stay private. 

I tried adding the Figaro gem to dashing and the values are not being pushed through.

**Comment by michaelachrisco** [comment]
What I have now is: 
```Ruby
    load_params = YAML::load_file('config/application.yml')
    github_params = load_params['github'].symbolize_keys

    @token = github_params[:github_token]
    @user = github_params[:github_user]
    @org = github_params[:github_org]
```

and a config/application.yml with:
```
github:
  github_token: token
  github_user: me
  github_org: my_work
```
